# Site settings
title: settings
name: rudy yang # your name
email: haiyuan1832@163.com # your email address
description: >
    rudy's github pages
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://suogongy.github.io" # the base hostname & protocol for your site
github_username: suogongy # your Github username

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
