# Site settings
title: fence
name: 仰海元 # your name
email: haiyuan1832@163.com # your email address
description: >
    小小围栏，圈一些自己的足迹
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://suogongy.github.io" # the base hostname & protocol for your site
weibo_username: 537945691 # your weibo username
github_username: suogongy # your Github username
disqus_username: itisbenjamin # your disqus username

# Build settings
permalink: none
markdown: kramdown
