# Site settings
title: Rudy Blog
name: Rudy Yang # your name
email: haiyuan1832@163.com # your email address
description: >
    A Simple Jekyll Blog Theme. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://suogongy.github.io" # the base hostname & protocol for your site
weibo_username: 537945691 # your Twitter username
github_username: suogongy # your Github username
disqus_username: itisbenjamin # your disqus username

google-analytics: UA-75034651-1 # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
